Improving benchmark experience
mind-inria/mri-nufft-benchmark pull request #2
Opened 2024-07-25 11:14 UTC by Lenoush

- A lot of code modification 
- Add creation data function file
- Add creation 2D trajs file
- Add creation of yalm file ( for doing all the backend , all traj , all n_coils is the same time: can be do with hydra , i didn't know but the script is cool)
- Add graphs in Readme : waiting for comments

2024-08-05 14:00 UTC, chaithyagr commented on result3D_cpu.png
We dont need pea GPU memory for all CPU versions

2024-08-05 14:20 UTC, paquiteau reviewed
Nice Work ! Figures looks very promising. 
Ideally we need more documentation in each file (a module docstring will do). Let's have in mind that this benchmark could be run by anyone.

2024-08-05 14:20 UTC, paquiteau commented on 0_create_data.py
Name this `05_create_data.py` The number in front, tells in which order to run the scripts.

2024-08-05 14:20 UTC, paquiteau commented on 50_auto_benchmark_perf.py
similarly remove the `50_`, this is a standalone file.

2024-08-05 14:29 UTC, Lenoush commented on 0_create_data.py
we don't get the image before get the trajs ?

2024-08-06 13:59 UTC, chaithyagr commented
I will let @paquiteau handle this PR's review.

2024-08-06 14:22 UTC, paquiteau requested changes
Congrats, the figures are really nice. 
In the README, write the exact commands you had to run to produce the results figures from start to finish, so that we can rerun the benchmark if any backend gets performance improvements

2024-09-05 13:18 UTC, paquiteau requested changes
We still need the exact commands you ran for getting those figures :)

2024-09-10 08:23 UTC, merged